apiRules:
- include:
    uidRegex: ^Gameplay
    type: Namespace
- include:
    uidRegex: ^ScriptableObjects
    type: Namespace
- include:
    uidRegex: ^Util
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace